
--Insert Statements 

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (1,'Broadsea Fish Bar','Fish and Chips',166,230,'restaurant','12pm - 11pm Daily','231 Sea View Rd','Broadsea','BE10 1NS','013405428831',' ');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (2,'M.Notarianni','Ice Cream Parlour',166,259,'cafe','10am-7pm Daily','259 Sea View Rd','Broadsea','BE10 1NS','013405765583','uywp@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (3,'V.Trembath','Fish Merchant',176,292,'shop','11.30 - 2pm and 6pm - 10pm Daily','291 Sea View Rd','Broadsea','BE10 2NS','013403589435','qqvp@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (4,'Starbucks','Coffee Bar',177,311,'cafe','8am-8pm Daily','311 Sea View Rd','Broadsea','BE10 2NS','013404009404','ciin@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (5,'Jolly Roger','Public House',180,375,'pub','10am-11pm Daily','375 Sea View Rd','Broadsea','BE10 2NS','013405852232',' ');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (6,'GT News','Newsagent',181,414,'shop','6am-5pm Daily','413 Sea View Rd','Broadsea','BE10 3NS','013404405597','ufnk@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (7,'Card World','Greeting Cards',183,467,'shop','9-5 Mon-Sat','467 Sea View Rd','Broadsea','BE10 3NS','013402440318',' ');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (8,'J.R.Hartley','Angling Supplies',216,34,'shop','9-5 Mon-Sat','17 Harbour Terrace','Broadsea','BE10 4NS','013405282703','vkhu@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (9, 'Taj Mahal','Restaurant',345,255,'restaurant','6pm-2am Daily','1 Angel Street','Broadsea','BE14 1AS','013404010207','lftp@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (10,'Shipley Travel','Travel Agent',461,209,'shop','9-5 Mon-Sat','208 High Street','Broadsea','BE13 5HS','013403460276','jvsl@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (11,'Coop','Supermarket',461,278,'supermarket','9am-10pm Daily','278 High Street','Broadsea','BE13 5HS','013401634339',' ');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (12,'Tesco','Supermarket',461,350,'supermarket','24 hrs Mon-Sat','350 High Street','Broadsea','BE13 5HS','013405547485',' ');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (13,'Starbucks','Coffee Bar',461,368,'caf�','8am-8pm Daily','368 High Street','Broadsea','BE13 5HS','013405671370','rrxk@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (14,'Pet World','Pet Store',461,406,'shop','9-5 Mon-Sat','406 High Street','Broadsea','BE13 5HP','013403541777','scyf@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (15,'E.Sockett','Electrical Dealer',461,482,'shop','9-5 Mon-Fri','482 High Street','Broadsea','BE13 5HP','013402498617','rcnc@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (16,'H.Mendrake','Fish and Chips',461,528,'shop','9-5 Mon-Sat','528 High Street','Broadsea','BE13 5HP','013402714015',' ');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (17,'Helen Dearnley','Toys and Game Store',461,540,'shop','9-5 Mon-Sat','540 High Street','Broadsea','BE13 5HP','013402651317','oxon@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (18,'I.Killit','Pest Control Specialist',478,241,'shop','9-5 Mon-Sat','241 High Street','Broadsea','BE13 5HS','013402984147','pbuq@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (19,'GT News','Newsagent',478,284,'shop','6am-5pm Daily','283 High Street','Broadsea','BE13 5HS','013405448591',' ');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (20,'Broadsea Arcade and Emporium','Entertainment Arcade',478,311,'shop','9-5 Mon-Sat','311 High Street','Broadsea','BE13 5HS','013402579182','jvim@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (21,'John Dace','Fish and Chips',478,325,'shop','9-5 Mon-Sat','325 High Street','Broadsea','BE13 5HS','013404249306',' ');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (22,'Jenny Targeter','Ladies Fashion and Shoes',479,255,'shop','7am-5pm Mon - Sat ','255 High Street','Broadsea','BE13 5HS','013405445802','vbod@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (23,'Waterstones','Bookshop',479,442,'shop','9-5 Mon-Sat','443 High Street','Broadsea','BE13 5HP','013402998442','uaoq@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (24,'Binns','Department Store',479,594,'department store','9-5 Mon-Sat','593 High Street','Broadsea','BE13 5HP','013403830133','jgze@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (25,'Rose and C n','Public House',612,231,'pub','10am-11pm Daily','231 Broad Street','Broadsea','BE15 2BS','013402687902',' ');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (26,'DBS','Furniture Store',613,288,'showroom','9-5 Daily','287 Broad Street','Broadsea','BE15 2BS','013404028987','mlpq@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (27,'Targeter Bros','Shoe Warehouse',616,621,'factory','n/a','621 Broad Street','Broadsea','BE15 2BS','013405700892','tprg@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (28,'Flash Harry Motors','Motor Dealer',655,332,'showroom','9am-5pm Daily','655 Sanctuary Avenue','Broadsea','BE15 2SA','013405530549','uwmw@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (29,'P.Henderson','Computer Sales and Repairs',672,332,'business unit','n/a','671 Sanctuary Avenue','Broadsea','BE15 2SA','013402275904','dipf@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (30,'Trevor Bacon','Builders Merchant',825,593,'warehouse','10-6 Mon-Fri  9-12 Sat','824 Museum Avenue','Broadsea','BE15 2MA','013405719394','tsua@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (31,'Blackrock and Co','Sweets and Novelties',873,593,'yard','9-5 Mon-Fri','872 Museum Avenue','Broadsea','BE15 2MA','013403242938',' ');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (32,'Fishermans Inn','Public House',540,92,'pub','10am-11pm Daily','Deve View Rd','Broadsea','BE 13 3PP','013405547484','');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (33,'Broadsea Omnibus Co','Public Transport Company',539,20,'office','9-5 Mon-Fri','Old Tram Sheds, Harbour Lane','Broadsea','BE13 5TV','08000257777','bboc@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, OPENING, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL)
VALUES (34,'Coastal Coaches Co','Public Transport Company',NULL,NULL,'office',NULL,'Tower House, High St','Preston','PR1 2VS','08450775661','cococo@gmail.com');

-- dans inserts 
INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (35,'Town Hall', 360,503, 'The Town Hall', 'Town Square', 'Broadsea','BE1 1TS','013401231231','admin@broadseatelco.com', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (36,'Main Post Office', 462,120, 'The Post Office', '116 High Street', 'Broadsea','BE13 5HS','013401235642','po@broadseatelco.com', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (37,'Fire Station', 480,380, 'The Fire Station', '377 High Street', 'Broadsea','BE13 5HP','013401239872','fire@broadseatelco.com', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (38,'Broadsea Omnibus Co Terminus', 539,20, 'Broadsea Bus Co. ', '300 Harbour Lane', 'Broadsea','BE13 5TV','013406665551','bbc@broadseatelco.com', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (39,'Police Station', 610,319, 'The Police Station', '325 Broad Street', 'Broadsea','BE17 4KL','013409900990','cops@broadseatelco.com', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (40,'GTA Taxi Co', 698,59, 'Gordon and Tom Arnold Taxis', '27 Station Road', 'Broadsea','BE17 2XY','08000235656','btc@broadseatelco.com', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (41,'Railway Station', 710,71, 'Broadsea Railway Station', 'Station Road', 'Broadsea','BE17 2XY','01340779872','trains@broadseatelco.com', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (42,'Broadsea Airport Transfers', 937,-200, 'Broadsea Airport Transfers', '17 Moor Hall Rd', 'Broadsea','BE18 1RA','013402312274','alanBDSX@broadseatelco.com', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (43,'Seaside Cabs', 1257,316, 'Seaside Cabs', 'Unit 18, Sealands Business Park', 'Nar sea','BE25 1TS','08001212121','seaside@broadseatelco.com', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (44,'Public Toilet', 160,509, '', 'Sea View Road', '', 'Broadsea','',NULL,'', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (45,'Public Toilet', 170,108, '', 'Barclay Street', '', 'Broadsea','',NULL,'', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (46,'Car Park A', 180,90, 'Municipal Car Park', 'Barclay Street', '', 'Broadsea','',NULL,'', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (47,'Car Park B', 200,510, 'Municipal Car Park', 'Broadway', '', 'Broadsea','',NULL,'', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (48,'Car Park C', 311,640, 'Municipal Car Park', 'Clarendon Road South', '', 'Broadsea','',NULL,'', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (49,'Public Toilet', 342,460, '', 'Town Square', '', 'Broadsea','',NULL,'', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (50,'Museum', 370,577, 'Broadsea Museum of Everything', 'St Thomas House', 'Museum Avenue', 'Broadsea','BE18 2HD','013404079458','', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (51,'Multi Storey Car Park', 477,500, 'NCP Car Parks', '501 High Street', '', 'Broadsea','','013401763102','', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (52,'Central Library', 530,260, 'The Central Library', '125 - 145 Angel Street', '', 'Broadsea','BE12 2XY','013405892818','lib@broadseatelco.com', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (53,'Sport Centre', 539,660, 'Treadmill Sport Centre', '50 Carver Lane', '', 'Broadsea','BE18 2BB','013404781458','sport@broadseatelco.com', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (54,'St Bartolphs Catholic  Church', 560,672, 'St Bartolphs Church', 'Carver Lane', '', 'Broadsea','BE18 2BB',NULL,'', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE)
VALUES (55,'St Anns Church (CofE)', 265,498, 'St Anns Church', 'Broadway', '', 'Broadsea','',NULL,'', 'Amenity');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE, RANKNO)
VALUES (56,'Station Taxi Rank (GTA)', 689,59, '', 'Station Rd', '', 'Broadsea','',NULL,'', 'Amenity',1);

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE,RANKNO)
VALUES (57,'Grand Hotel Taxi Rank', 294,311, 'The Grand Hotel', 'John St', '', 'Broadsea','',NULL,'', 'Amenity',2);

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE,RANKNO)
VALUES (58,'Oasis Taxi Rank', 221,611, 'The Oasis Theatre', 'Broad Park', '', 'Broadsea','',NULL,'', 'Amenity',3);

INSERT INTO BBT_DESTINATION (DESTID, NAMES, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, PHONE, EMAIL, PLACETYPE,RANKNO)
VALUES (59,'Town Square Taxi Rank', 336,528, '', 'Town Square', '', 'Broadsea','',NULL,'', 'Amenity',4);

--ben shaws inserts
INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE,  ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (60,'Lighthouse','Attraction',50,650,'The Old Lighthouse','648 Sea View Rd', 'Broadsea',NULL ,NULL,NULL);

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (61,'Shipwreck of SS Salt','Attraction',54,577,NULL,'Broadsea Beach', 'Broadsea',NULL ,NULL,NULL);

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (62,'Donkey Rides','Attraction',129,61,NULL,'Broadsea Beach', 'Broadsea',NULL ,NULL,NULL);

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (63,'Punch and Judy','Attraction',129,170,NULL,'Broadsea Beach', 'Broadsea',NULL ,NULL,NULL);

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (64,'Jet Ski Hire','Attraction',129,511,NULL,'Broadsea Beach', 'Broadsea',NULL ,'013402495311','tbzn@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (65,'Broad Park Boating Lake','Attraction',139,699,NULL,'Broad Park', 'Broadsea',NULL ,NULL,NULL);

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (66,'Crazy Golf Course','Attraction',161,430,NULL,'Broadsea Beach', 'Broadsea',NULL ,NULL,NULL);

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (67,'Broadsea Yacht Club','Attraction',172,19,'Broadsea Yacht Club','9 Harbour Terrace', 'Broadsea','BE10 2CU', '013403421680','egti@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (68,'Broadsea Aquarium','Attraction',239,340,'The Aquarium','45 Arcadia Gardens', 'Broadsea','BE13 3TG','013403910779','xqir@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (69,'Oasis Theatre','Attraction',241,629,'The Oasis Theatre','Broad Park Circle', 'Broadsea','BE20 1CU','013403166535','lzmf@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (70,'Botanical Gardens','Attraction',271,512,'Botanical Gardens','Clarendon Road South', 'Broadsea',NULL,NULL, NULL);

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (71,'Odeon Cinema','Attraction',329,388,'The Odeon Cinema','374 Clarendon Road North','BE11 2JJ', 'Broadsea','013402217566', 'qmvb@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (72,'Statue of Sir Thomas Broad','Attraction',336,500,NULL ,'Town Square', 'Broadsea', NULL,NULL, NULL);

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (73,'Screamers Fun Fair','Attraction',342,61,'Screamers Fun Fair','Clarendon Road North', 'Broadsea','BE10 2FF','013402217431', 'unpf@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (74,'Pearl Cinema','Attraction',480,162,'The Pearl Cinema','163 High Street', 'Broadsea','BE14 7TT','013402286626', 'rwdv@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (75,'The Planetarium','Attraction',612,460,'The Planetarium','463 Broad Street', 'Broadsea','BE16 1AS','013404697585', 'jfzo@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (76,'Valley Greyhound Stadium','Attraction',650,570,'Valley Dogs Ltd','320 Museum Avenue', 'Broadsea','BE17 6GA', '013401728533', 'wvtl@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (77,'Oaks Golf Club','Attraction',700,420,'The Oaks Golf Club','off Museum Avenue', 'Broadsea','BE17 6GG','013403945641', 'eifm@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (78,'Taylor Chocolate Co.','Attraction',772,570,'AJP Taylor and Co Ltd','500 Museum Avenue', 'Broadsea','BE17 6GF','013401840407', 'yasi@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (79,'Broadsea Donkey Sanctuary','Attraction',790,331,'Broadsea Donkey Sanctuary','450 Sanctuary Avenue', 'Broadsea','BE17 2XY','013405508219', 'monv@broadseatelco.com');

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (80,'Broadsea Pony and Trap','Attraction',751,337,'Broadsea Pony and Trap','442 Sanctuary Avenue', 'Broadsea','BE17 2XY','077812187355', NULL);

INSERT INTO BBT_DESTINATION (DESTID,NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, ADDRESSLINE1, ADDRESSLINE2,ADDRESSLINE3, POSTCODE, PHONE, EMAIL)
VALUES (81,'Napoleons Casino','Attraction',174,246,'Napoleons','Sea View Rd', 'Broadsea','BE10 1NS','013403948841', 'winhere@broadseatelco.com');

--bens muligans inserts 
INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (82, 'Grand Hotel', 'Hotel', 309, 308, 'Hotel', '115 John Street', 'BroadSea', 'BE17 2XY', '013401868802', 'grno@broadseatelco.com', '5 Star');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (83, 'Bay View Hotel', 'Hotel', 198, 281, 'Hotel', 'Sea View Road', 'BroadSea', 'BE10 1NS', '013402094520', 'mfzp@broadseatelco.com', '4 Star');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (84, 'BroadSea Hilton', 'Hotel', 198, 252, 'Hotel', 'Sea View Road', 'BroadSea', 'BE10 1NS', '013403374106', 'bova@broadseatelco.com', '4 Star');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (85, 'Ye Olde Pirate', 'Hotel', 205, 406, 'Hotel', 'Sea View Road', 'BroadSea', 'BE10 2NS', '013402085232', 'wptx@broadseatelco.com', '3 Star');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (86, 'Premier Inn', 'Hotel', 208, 436, 'Hotel', 'Sea View Road', 'BroadSea', 'BE10 2NS', '013402733182', 'lazg@broadseatelco.com', '3 Star');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (87, 'Best Eastern', 'Hotel', 211, 490, 'Hotel', 'Sea View Road', 'BroadSea', 'BE10 2NS', '013402460489', 'hbhd@broadseatelco.com', '3 Star');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (88, 'SunnyView', 'B and B', 272, 48, 'B and B', 'Harbour Terrace', 'BroadSea', 'BE10 3NS', '013403025143', ' ', '3 Teacups');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (89, 'Harbour Rest', 'B and B', 243, 48, 'B and B', 'Harbour Terrace', 'BroadSea', 'BE10 3NS', '013404602125', 'vukc@broadseatelco.com', '4 Teacups');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (90, 'Home From Home', 'B and B', 250, 173, 'B and B', 'Carlton Terrace', 'BroadSea', 'BE10 4DF', '013405568640', 'relg@broadseatelco.com', '4 Teacups');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (91, 'Greenacres', 'B and B', 250, 265, 'B and B', 'Carlton Terrace', 'BroadSea', 'BE10 4DF', '013401317183', 'dxif@broadseatelco.com', '3 Teacups');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (92, 'Watership Down', 'B and B', 250, 307, 'B and B', 'Carlton Terrace', 'BroadSea', 'BE10 4DF', '013405034830', 'itvq@broadseatelco.com', '3 Teacups');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (93, 'Old Silver Bell', 'B and B', 232, 233, 'B and B', 'Carlton Terrace', 'BroadSea', 'BE10 4DF', '013403568299', 'exek@broadseatelco.com', '2 Teacups');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (94, 'Broadsea Roadhouse', 'Motel', 780, 756, 'Motel', 'York Road', 'BroadSea', 'BE21 5LK', '013403073764', 'swwl@broadseatelco.com', '3 Star');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (95, 'Travelodge', 'Motel', 666, 778, 'Motel', 'York Road', 'BroadSea', 'BE21 5LK', '013403995915', 'yohh@broadseatelco.com', '2 Star');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (96, 'Warm Heart Guesthouse', 'Guesthouse', 312, 191, 'Guesthouse', 'Oldfield Road', 'BroadSea', 'BE11 2FR', '013402253148', ' ', 'N/A');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (97, 'Happy Days Caravan  and  Camping park', 'Caravnan  and  Camping Park', 888, 45, 'caravan  and  Camping Park', 'Station Road', 'BroadSea', 'BE23 2TS', '013403871785', 'rgiz@broadseatelco.com', '4 Tents');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (98, 'Rosemary  and  Thyme', 'B and B', 314, 224, 'B and B', 'Oldfield Road', 'BroadSea', 'BE11 2FR', '013404309298', 'hwtp@broadseatelco.com', '4 Teacups');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (99, 'Seaview', 'B and B', 314, 244, 'B and B', 'Oldfield Road', 'BroadSea', 'BE11 2FR', '013404047856', 'uonf@broadseatelco.com', '3 Teacups');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (100, 'Blue Horizon', 'B and B', 314, 255, 'B and B', 'Oldfield Road', 'BroadSea', 'BE11 2FR', '013405436914', ' ', '4 Teacups');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (101, 'Cozee Comfort', 'B and B', 400, 433, 'B and B', '48 Dyke Lane', 'BroadSea', 'BE12 1FE', '013405090622', 'sxer@broadseatelco.com', '3 Teacups');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (102, 'Dunbathin', 'B and B', 420, 433, 'B and B', '52 Dyke Lane', 'BroadSea', 'BE12 1FF', '013401885377', 'imqe@broadseatelco.com', '3 Teacups');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (103, 'Dunfishin', 'B and B', 440, 433, 'B and B', '56 Dyke Lane', 'BroadSea', 'BE12 1FF', '013405704598', 'jktd@broadseatelco.com', '3 Teacups');

INSERT INTO BBT_DESTINATION (DESTID, NAMES, PLACETYPE, XCOORDINATE, YCOORDINATE, LOCATION_DESCRIPTION, ADDRESSLINE1, ADDRESSLINE2, POSTCODE, PHONE, EMAIL, RATING)
VALUES (104, 'Broadsea Youth Hostel', 'Youth Hostel', 430, 450, 'Youth Hostel', '57 Dyke Lane', 'BroadSea', 'BE12 1FF', '013405919813', 'jjns@broadseatelco.com', 'N/A');

--BUSSTOPS IMPORTS FOR DESTINATION
--Row 1
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (371,237.0,366.0,'Aquarium','Arcadia Gdns', 'BusStop');
--Row 2
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (374,218.0,398.0,'Arcadia Gdns','Arcadia Gdns', 'BusStop');
--Row 3
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (377,237.0,475.0,'Arcadia Gdns','Arcadia Gdns', 'BusStop');
--Row 4
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (380,248.0,92.0,'Barclay St','Barclay St', 'BusStop');
--Row 5
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (383,613.0,133.0,'Station Rd','Broad St', 'BusStop');
--Row 6
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (386,594.0,150.0,'Station Rd','Broad St', 'BusStop');
--Row 7
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (389,614.0,222.0,'Rose  and  Crown','Broad St', 'BusStop');
--Row 8
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (392,595.0,233.0,'Rose  and  Crown','Broad St', 'BusStop');
--Row 9
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (395,614.0,302.0,'Police Station','Broad St', 'BusStop');
--Row 10
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (398,595.0,316.0,'Police Station','Broad St', 'BusStop');
--Row 11
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (401,596.0,396.0,'Dyke Lane','Broad St', 'BusStop');
--Row 12
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (404,615.0,399.0,'Dyke Lane','Broad St', 'BusStop');
--Row 13
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (407,614.0,488.0,'Planetarium','Broad St', 'BusStop');
--Row 14
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (410,596.0,499.0,'Planetarium','Broad St', 'BusStop');
--Row 15
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (413,597.0,627.0,'Targeters','Broad St', 'BusStop');
--Row 16
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (416,617.0,637.0,'Targeters','Broad St', 'BusStop');
--Row 17
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (419,534.0,676.0,'Sport Centre','Carver Lane', 'BusStop');
--Row 18
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (422,534.0,676.0,'Sport Centre','Carver Lane', 'BusStop');
--Row 19
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (425,345.0,121.0,'Dene View Rd','Clarendon Rd N', 'BusStop');
--Row 20
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (428,327.0,133.0,'Barclay St','Clarendon Rd N', 'BusStop');
--Row 21
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (431,343.0,232.0,'Angel St','Clarendon Rd N', 'BusStop');
--Row 22
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (434,327.0,247.0,'Angel St','Clarendon Rd N', 'BusStop');
--Row 23
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (437,345.0,330.0,'Grand Hotel','Clarendon Rd N', 'BusStop');
--Row 24
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (440,326.0,374.0,'Odeon','Clarendon Rd N', 'BusStop');
--Row 25
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (443,344.0,442.0,'Dyke Lane','Clarendon Rd N', 'BusStop');
--Row 26
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (446,347.0,606.0,'Museum Ave','Clarendon Rd S', 'BusStop');
--Row 27
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (449,329.0,622.0,'Botanical Gdns','Clarendon Rd S', 'BusStop');
--Row 28
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (452,405.0,91.0,'Dene View Rd','Dene View Rd', 'BusStop');
--Row 29
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (455,540.0,92.0,'Fishermans Inn','Dene View Rd', 'BusStop');
--Row 30
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (458,516.0,5.0,'Terminus','Harbour Lane', 'BusStop');
--Row 31
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (461,357.0,6.0,'Clarendon Rd N','Harbour Lane', 'BusStop');
--Row 32
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (464,492.0,23.0,'Terminus','Harbour Lane', 'BusStop');
--Row 33
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (467,637.0,58.0,'Harbour Lane','Harbour Lane', 'BusStop');
--Row 34
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (470,656.0,59.0,'Harbour Lane','Harbour Lane', 'BusStop');
--Row 35
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (473,176.0,5.0,'Yacht Club','Harbour Terrace', 'BusStop');
--Row 36
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (476,199.0,24.0,'Yacht Club','Harbour Terrace', 'BusStop');
--Row 37
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (479,306.0,24.0,'Clarendon Rd N','Harbour Terrace', 'BusStop');
--Row 38
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (482,479.0,135.0,'High St Pearl','High St', 'BusStop');
--Row 39
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (485,461.0,148.0,'High St PO','High St', 'BusStop');
--Row 40
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (488,479.0,223.0,'Shipley Travel','High St', 'BusStop');
--Row 41
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (491,461.0,229.0,'Shipley Travel','High St', 'BusStop');
--Row 42
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (494,479.0,296.0,'Arcade','High St', 'BusStop');
--Row 43
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (497,460.0,305.0,'Arcade','High St', 'BusStop');
--Row 44
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (500,460.0,385.0,'Fire Station','High St', 'BusStop');
--Row 45
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (503,481.0,396.0,'Fire Station','High St', 'BusStop');
--Row 46
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (506,479.0,643.0,'Carver Lane','High St', 'BusStop');
--Row 47
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (509,462.0,644.0,'Carver Lane','High St', 'BusStop');
--Row 48
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (512,246.0,293.0,'John St','John St', 'BusStop');
--Row 49
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (515,273.0,314.0,'John St','John St', 'BusStop');
--Row 50
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (518,553.0,574.0,'Museum Ave E','Museum Avenue', 'BusStop');
--Row 51
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (521,794.0,574.0,'Chocolate Factory','Museum Avenue', 'BusStop');
--Row 52
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (524,626.0,575.0,'Greyhound Stadium','Museum Avenue', 'BusStop');
--Row 53
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (527,535.0,593.0,'Museum Ave E','Museum Avenue', 'BusStop');
--Row 54
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (530,413.0,595.0,'Museum Ave W','Museum Avenue', 'BusStop');
--Row 55
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (533,648.0,595.0,'Greyhound Stadium','Museum Avenue', 'BusStop');
--Row 56
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (536,774.0,595.0,'Chocolate Factory','Museum Avenue', 'BusStop');
--Row 57
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (539,257.0,580.0,'Oasis North','Oasis', 'BusStop');
--Row 58
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (542,208.0,678.0,'Oasis South','Oasis', 'BusStop');
--Row 59
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (545,717.0,111.0,'Station','Railway Rd', 'BusStop');
--Row 60
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (548,674.0,117.0,'Station','Railway Rd', 'BusStop');
--Row 61
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (551,804.0,305.0,'Sanctuary','Railway Rd', 'BusStop');
--Row 62
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (554,833.0,323.0,'Sanctuary','Railway Rd', 'BusStop');
--Row 63
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (557,537.0,331.0,'Sanctuary Avenue E','Sanctuary Avenue', 'BusStop');
--Row 64
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (560,430.0,332.0,'Sanctuary Avenue W','Sanctuary Avenue', 'BusStop');
--Row 65
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (563,410.0,352.0,'Sanctuary Avenue W','Sanctuary Avenue', 'BusStop');
--Row 66
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (566,543.0,354.0,'Sanctuary Avenue E','Sanctuary Avenue', 'BusStop');
--Row 67
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (569,148.0,80.0,'Car Park A','Sea View Rd', 'BusStop');
--Row 68
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (572,165.0,123.0,'Barclay St','Sea View Rd', 'BusStop');
--Row 69
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (575,147.0,177.0,'North Beach','Sea View Rd', 'BusStop');
--Row 70
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (578,165.0,186.0,'Bay Hotel','Sea View Rd', 'BusStop');
--Row 71
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (581,165.0,245.0,'Casino','Sea View Rd', 'BusStop');
--Row 72
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (584,153.0,275.0,'John St','Sea View Rd', 'BusStop');
--Row 73
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (587,177.0,339.0,'John St','Sea View Rd', 'BusStop');
--Row 74
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (590,162.0,370.0,'Central Beach','Sea View Rd', 'BusStop');
--Row 75
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (593,182.0,440.0,'Crazy Golf','Sea View Rd', 'BusStop');
--Row 76
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (596,166.0,479.0,'Broadway','Sea View Rd', 'BusStop');
--Row 77
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (599,163.0,552.0,'Botanical Gdns','Sea View Rd', 'BusStop');
--Row 78
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (602,118.0,574.0,'Shipwreck','Sea View Rd', 'BusStop');
--Row 79
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (605,73.0,666.0,'Broad Park Lake','Sea View Rd', 'BusStop');
--Row 80
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (608,50.0,678.0,'Lighthouse','Sea View Rd', 'BusStop');
--Row 81
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (611,796.0,26.0,'Bridge','Station Rd', 'BusStop');
--Row 82
INSERT INTO BBT_DESTINATION (DESTID,  XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (614,308.0,490.0,'Town Hall','Town Square', 'BusStop');
--Row 83
INSERT INTO BBT_DESTINATION (DESTID,  XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (617,364.0,519.0,'Town Hall','Town Square', 'BusStop');
--Row 84
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (620,374.0,733.0,'Clarendon Rd S','York Rd', 'BusStop');
--Row 85
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (623,524.0,734.0,'High St','York Rd', 'BusStop');
--Row 86
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (626,724.0,734.0,'Town End','York Rd', 'BusStop');
--Row 87
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (629,901.0,735.0,'Railway Rd','York Rd', 'BusStop');
--Row 88
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (632,197.0,736.0,'Broad Park','York Rd', 'BusStop');
--Row 89
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (635,173.0,753.0,'Broad Park','York Rd', 'BusStop');
--Row 90
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (638,566.0,753.0,'Broad St','York Rd', 'BusStop');
--Row 91
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (641,763.0,753.0,'Town End','York Rd', 'BusStop');
--Row 92
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (644,357.0,754.0,'Clarendon Rd S','York Rd', 'BusStop');
--Row 93
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (647,928.0,754.0,'Railway Rd','York Rd', 'BusStop');
--Row 94
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (650,461.0,559.0,'Museum Ave','High St', 'BusStop');
--Row 95
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (653,461.0,465.0,'High St Car Park','High St', 'BusStop');
--Row 96
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (656,482.0,483.0,'High St Car Park','High St', 'BusStop');
--Row 97
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (659,480.0,567.0,'Museum Ave','High St', 'BusStop');
--Row 98
INSERT INTO BBT_DESTINATION (DESTID, XCOORDINATE, YCOORDINATE, NAMES, LOCATEDON, PLACETYPE) VALUES (662,404.0,573.0,'Museum','Museum Avenue', 'BusStop');

--PHV LICENSES
INSERT INTO BBT_LICENSEE (DESTID,LICENSENO, LICENSETYPE, VALIDFROM, EXPIRYDATE, NAMES) VALUES (40,586,'Taxi','01/jan/2012','31/dec/2015','GTA Taxis');

INSERT INTO BBT_LICENSEE (DESTID,LICENSENO, LICENSETYPE, VALIDFROM, EXPIRYDATE, NAMES) VALUES (42,635,'Minicab','05/jun/2013','04/apr/2016','Broadsea Airport Transfers');

INSERT INTO BBT_LICENSEE (DESTID,LICENSENO, LICENSETYPE, VALIDFROM, EXPIRYDATE, NAMES) VALUES (43,257,'Taxi','21/nov/2013','20/nov/2016','Seaside Cabs');

INSERT INTO BBT_LICENSEE (DESTID,LICENSENO, LICENSETYPE, VALIDFROM, EXPIRYDATE, NAMES) VALUES (80,137,'Leisure','04/apr/2014','04/mar/2016','Broadsea Pony and Trap');

--PHV LICENSES
--  1
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('GTA Taxis','586-001','AC08 HNR','Ford Mondeo Est',4.0,'10:00','10:00','Station',' ');
--  2
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('GTA Taxis','586-002','XG10 PQT','Ford Mondeo Est',4.0,'08:00','20:00','Station',' ');
--  3
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('GTA Taxis','586-003','PT13 AAC','Audi A4',4.0,'08:00','20:00','Grand Hotel',' ');
--  4
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('GTA Taxis','586-004','PR13 ADD','Audi A4',4.0,'08:00','20:00','Grand Hotel',' ');
--  5
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('Broadsea Airport Transfers','635-001','VX13 MYC','Citroen C4 Picasso',7.0,'n/a','n/a','n/a',' ');
--  6
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('Broadsea Airport Transfers','635-002','DX10 TTY','Vauxhall Safira',5.0,'n/a','n/a','n/a',' ');
--  7
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('Seaside Cabs','257-001','SSC 001','TXII',5.0,'10:00','10:00','Station',' ');
--  8
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('Seaside Cabs','257-002','SSC 003','TXII',5.0,'08:00','20:00','Station',' ');
--  9
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('Seaside Cabs','257-003','SSC 008','TXII',5.0,'08:00','20:00','Town Square',' ');
--  10
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('Seaside Cabs','257-004','SSC 216','TXII',5.0,'12:00','20:00','Town Square',' ');
--  11
-- not entered due to same registration as above one, ask john about this
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('Seaside Cabs','257-005','SSC 216','TXII',5.0,'20:00','11:00','Oasis ',' ');
--  12
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('Seaside Cabs','257-006','GR13 APV','TX4',5.0,'08:00','20:00','Grand Hotel',' ');
--  13
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('Seaside Cabs','257-007','GR13 APW','TX4',5.0,'08:00','20:00','Grand Hotel',' ');
--  14
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('Broadsea Pony and Trap','137-001','Juno','Horse-drawn carriage',4.0,' ',' ','Car Park B',' ');
--  15
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('Broadsea Pony and Trap','137-002','Betty','Horse-drawn carriage',4.0,' ',' ','Car Park B',' ');
--  16
INSERT INTO BBT_VEHICLE (OPERATOR, REFERENCE, REGISTRATION, VEHICLETYPE,  capacity, TIMEON, TIMEOFF, HOMERANK, MODELS) VALUES ('Broadsea Pony and Trap','137-003','Dobbin','Horse-drawn carriage',4.0,' ',' ','Car Park B',' ');

/*Licensed Vehicle*/

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (586, 'AC08 HNR', '586-001');

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (586, 'XG10 PQT', '586-002');

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (586, 'PT13 AAC', '586-003');

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (586, 'PR13 ADD', '586-004');

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (635, 'VX13 MYC', '635-001');

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (635, 'DX10 TTY', '635-002');

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (257, 'SSC 001', '257-001');

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (257, 'SSC 003', '257-002');

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (257, 'SSC 008', '257-003');

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (257, 'SSC 216', '257-004');

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (257, 'SSC 216', '257-005');

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (257, 'GR13 APV', '257-006');

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (257, 'GR13 APW', '257-007');

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (137, 'Juno', '137-001');

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (137, 'Betty', '137-002');

INSERT INTO BBT_Licenced_Vehicle (LicenseNo, Registration, REFERENCE)
VALUES (137, 'Dobbin', '137-003');



--SHEDULE

INSERT INTO BBT_SCHEDULE (DESTID,SCHEDULENO, TYPE1, STARTDATE, ENDDATE, OPERATORS, OPERATORLICENSENO, EXPIRYDATE, ROUTENO, BASEFARE, FAREPERSTOP) 
VALUES (34,785.0, 'Regional', to_date('01/jan/2013'), to_date('31/dec/2016'), 'Coastal Coaches Co', 1904956.0, to_date('12/may/2018'), 'X91', 'n/a', 'n/a');

INSERT INTO BBT_SCHEDULE (DESTID,SCHEDULENO, TYPE1, STARTDATE, ENDDATE, OPERATORS, OPERATORLICENSENO, EXPIRYDATE, ROUTENO, BASEFARE, FAREPERSTOP) 
VALUES (33,3871.0, 'Local', to_date('01/sep/2014'), to_date('31/aug/2015'), 'Broadsea Omnibus Co', 201358.0, to_date('31/mar/2017'), '20, 30', '40p', '10p');

INSERT INTO BBT_SCHEDULE (DESTID,SCHEDULENO, TYPE1, STARTDATE, ENDDATE, OPERATORS, OPERATORLICENSENO, EXPIRYDATE, ROUTENO, BASEFARE, FAREPERSTOP) 
VALUES (33,3888.0, 'Local', to_date('01/sep/2014'), to_date('31/aug/2015'), 'Broadsea Omnibus Co', 201358.0, to_date('31/mar/2017'), '55, 65', '40p', '10p');

INSERT INTO BBT_SCHEDULE (DESTID,SCHEDULENO, TYPE1, STARTDATE, ENDDATE, OPERATORS, OPERATORLICENSENO, EXPIRYDATE, ROUTENO, BASEFARE, FAREPERSTOP) 
VALUES (34,654.0, 'Regional', to_date('01/jan/2013'), to_date('31/dec/2016'), 'Coastal Coaches Co', 1904956.0, to_date('12/may/2018'), 'X3', 'n/a', 'n/a');

--freq

/*FREQUENCY*/

INSERT INTO BBT_Frequency(Route, Days, Frequency, Starts, Ends)
VALUES ('X91', 'Weekdays', 30, '07:30', '22:00');

INSERT INTO BBT_Frequency(Route, Days, Frequency, Starts, Ends)
VALUES ('X91', 'Sat', 60, '08:30', '22:00');

INSERT INTO BBT_Frequency(Route, Days, Frequency, Starts, Ends)
VALUES ('X3', 'Weekdays', 20, '07:30', '22:00');

INSERT INTO BBT_Frequency(Route, Days, Frequency, Starts, Ends)
VALUES ('X3', 'Sat', 20, '08:30', '22:00');

INSERT INTO BBT_Frequency(Route, Days, Frequency, Starts, Ends)
VALUES ('20', 'Weekdays', 10, '06:00', '23:00');

INSERT INTO BBT_Frequency(Route, Days, Frequency, Starts, Ends)
VALUES ('20', 'Sat', 15, '07:00', '22:00');

INSERT INTO BBT_Frequency(Route, Days, Frequency, Starts, Ends)
VALUES ('20', 'Sun', 20, '08:00', '20:00');

INSERT INTO BBT_Frequency(Route, Days, Frequency, Starts, Ends)
VALUES ('30', 'Weekdays', 10, '07:30', '22:00');

INSERT INTO BBT_Frequency(Route, Days, Frequency, Starts, Ends)
VALUES ('30', 'Sat', 10, '07:30', '22:00');


INSERT INTO BBT_Frequency(Route, Days, Frequency, Starts, Ends)
VALUES ('55', 'Weekdays', 10, '07:00', '23:00');

INSERT INTO BBT_Frequency(Route, Days, Frequency, Starts, Ends)
VALUES ('55', 'Sat', 15, '07:00', '22:00');

INSERT INTO BBT_Frequency(Route, Days, Frequency, Starts, Ends)
VALUES ('55', 'Sun', 20, '08:00', '20:00');

INSERT INTO BBT_Frequency(Route, Days, Frequency, Starts, Ends)
VALUES ('65', 'Weekdays', 10, '07:30', '22:00');

INSERT INTO BBT_Frequency(Route, Days, Frequency, Starts, Ends)
VALUES ('65', 'Sat', 10, '07:30', '22:00');

INSERT INTO BBT_Frequency(Route, Days, Frequency, Starts, Ends)
VALUES ('65', 'Sun', 10, '07:30', '20:00');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X91', 'Railway Rd','548','Station', 0, 'OUT', 'X910');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X91', 'High Street','494','Arcade', 4, 'OUT', 'X91O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X91', 'Clarendon Rd N','617','Town Hall', 9, 'OUT', 'X91O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X91', 'Sea View Rd','599','Botanical Gdns', 12, 'OUT', 'X91O');

--in
INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X91', 'Sea View Rd','608','Lighthouse', 0, 'IN', 'X91I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X91', 'Clarendon Rd N','614','Town Hall', 3, 'IN', 'X91I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X91', 'High Street','491','Shipley Travel', 8, 'IN', 'X91I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X91', 'Railway Rd','545','Station 10', 0, 'IN', 'X91I');

--X3
--out
INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X3', 'Broad St','383','Station Rd', 0, 'OUT', 'X3O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X3', 'Broad St','395','Police Station', 2, 'OUT', 'X3O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X3', 'Sanctuary Ave W','563','Sanctuary Ave W', 4, 'OUT', 'X3O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X3', 'Town Square','617','Town Hall', 7, 'OUT', 'X3O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X3', 'Sea View Road','605','Broad Park Lake', 10, 'OUT', 'X3O');

--in
INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X3', 'Sea View Road','602','ShipWreck', 0, 'IN', 'X3I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X3', 'Town Square','614','Town Hall', 3, 'IN', 'X3I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X3', 'Sanctuary Ave','557','Sanctuary Ave E', 6, 'IN', 'X3I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X3', 'Broad St','386','Station Rd', 8, 'IN', 'X3I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO) 
VALUES ('X3', 'Station Rd','611','Bridge', 10, 'IN', 'X3I');

--20
--OUT

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Harbour Terrace', '458', 'Terminus', 0 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Harbour Lane', '470', 'Harbour Lane', 2 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Broad Street', '383', 'Station Rd', 4 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Broad Street', '389', 'Rose and Crown', 6 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Broad Street', '395', 'Police Station', 8 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Broad Street', '404', 'Dyke Lane', 10 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Broad Street', '407', 'Planetarium', 12 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Broad Street', '416', 'Targeters', 15 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'York Road', '638', 'Broad St', 18 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'York Road', '644', 'Clarendon Rd S', 21 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'York Road', '635', 'Broad Park', 23 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Sea View Road', '608', 'Lighthouse', 26 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Sea View Road', '602', 'Shipwreck', 28 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Sea View Road', '596', 'Broadway', 30 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Sea View Road', '590', 'Central Beach', 32 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Sea View Road', '584', 'John St', 34 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Sea View Road', '575', 'North Beach', 36 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Sea View Road', '569', 'Car Park A', 38 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Harbour Terrace', '473', 'Yacht Club', 39 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Harbour Terrace', '461', 'Fun Fair', 41 ,'OUT', '20O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Harbour Terrace', '458', 'Terminus', 43 ,'OUT', '20O');



--20
--IN

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Harbour Terrace', '464', 'Terminus', 0 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Harbour Terrace', '479', 'Clarendon Rd N', 2 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Harbour Terrace', '476', 'Yacht Club', 4 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Sea View Road', '572', 'Barclay St', 6 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Sea View Road', '578', 'Bay Hotel', 8 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Sea View Road', '581', 'Casino', 10 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Sea View Road', '587', 'John St', 12 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Sea View Road', '593', 'Crazy Golf', 15 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Sea View Road', '559', 'Botanical Gdns', 18 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Sea View Road', '605', 'Broad Park Lake', 21 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'York Road', '632', 'Broad Park', 23 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'York Road', '620', 'Clarendon Rd S', 26 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'York Road', '623', 'High St', 28 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Broad Street', '413', 'Targeters', 30 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Broad Street', '410', 'Planetarium', 32 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Broad Street', '401', 'Dyke Lane', 34 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Broad Street', '398', 'Police Station', 36 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Broad Street', '392', 'Rose and Crown', 38 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Broad Street', '386', 'Station Rd', 39 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Harbour Lane', '467', 'Harbour Lane', 41 ,'IN', '20I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('20', 'Harbour Terrace', '464', 'Terminus', 43 ,'IN', '20I');
 

--30
--OUT


INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Railway Rd', '548', 'Station', 0 ,'OUT', '30O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Broad Street', '383', 'Station Rd', 2 ,'OUT', '30O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Broad Street', '389', 'Rose and Crown', 4 ,'OUT', '30O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Broad Street', '395', 'Police Station', 6 ,'OUT', '30O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Broad Street', '404', 'Dyke Lane', 8 ,'OUT', '30O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'High Street', '500', 'Fire Station ', 11 ,'OUT', '30O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'High Street', '497', 'Arcade', 13 ,'OUT', '30O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'High Street', '485', 'High St PO', 15 ,'OUT', '30O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Clarendon Rd  N', '425', 'Dene View Rd', 18 ,'OUT', '30O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Clarendon Rd  N', '431', 'Angel St', 20 ,'OUT', '30O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Clarendon Rd  N', '437', 'Grand Hotel', 22 ,'OUT', '30O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Clarendon Rd  N', '443', 'Dyke Lane', 24 ,'OUT', '30O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Town Square', '617', 'Town Hall', 26 ,'OUT', '30O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Town Square', '614', 'Town Hall', 28 ,'OUT', '30O');
--30
--IN

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Town Square', '614', 'Town Hall', 0 ,'IN', '30I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Clarendon Rd  N', '440', 'Odeon', 2 ,'IN', '30I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Clarendon Rd  N', '434', 'Angel St', 4 ,'IN', '30I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Clarendon Rd  N', '428', 'Barclay St', 6 ,'IN', '30I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Dene View Road', '452', 'Dene View Road', 8 ,'IN', '30I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'High Street', '482', 'High St Pearl ', 11 ,'IN', '30I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'High Street', '488', 'Shipley Travel', 13 ,'IN', '30I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'High Street', '494', 'Arcade?', 15 ,'IN', '30I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'High Street', '503', 'Fire Station ', 17 ,'IN', '30I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Broad Street', '401', 'Dyke Lane', 20 ,'IN', '30I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Broad Street', '398', 'Police Station', 22 ,'IN', '30I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Broad Street', '392', 'Rose and Crown', 24 ,'IN', '30I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Broad Street', '386', 'Station Rd', 26 ,'IN', '30I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('30', 'Railway Rd', '545', 'Station', 28 ,'IN', '30I');
--55
--OUT

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'Oasis', '542', 'Oasis South', 0 ,'OUT', '55O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'Sea View Rd', '596', 'Broadway', 2 ,'OUT', '55O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'Sea View Rd', '590', 'Central Beach', 4 ,'OUT', '55O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'John St', '512', 'John St', 6 ,'OUT', '55O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'Clarendon Rd  N', '434', 'Angel St', 8 ,'OUT', '55O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'Clarendon Rd  N', '428', 'Barclay St', 10 ,'OUT', '55O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'Dene View Rd', '452', 'Dene View Rd', 12 ,'OUT', '55O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'High Street', '482', 'High St Pearl', 14 ,'OUT', '55O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'High Street', '488', 'Shipley Travel', 16 ,'OUT', '55O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'High Street', '494', 'Arcade', 18 ,'OUT', '55O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'High Street', '503', 'Fire Station ', 20 ,'OUT', '55O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'High Street', '656', 'High St Car Park', 22 ,'OUT', '55O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'High Street', '659', 'Museum Ave', 24 ,'OUT', '55O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'High Street', '506', 'Carver Lane', 26 ,'OUT', '55O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'York Rd', '644', 'Clarendon Rd S', 28 ,'OUT', '55O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'Oasis', '542', 'Oasis South', 30 ,'OUT', '55O');
--55
--IN

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'Oasis', '539', 'Oasis North', 0 ,'IN', '55I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'York Rd', '620', 'Clarendon Rd S', 2 ,'IN', '55I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'High Street', '509', 'Carver Lane', 4 ,'IN', '55I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'High Street', '653', 'Museum Ave', 6 ,'IN', '55I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'High Street', '650', 'High St Car Park', 8 ,'IN', '55I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'High Street', '500', 'Fire Station ', 10 ,'IN', '55I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'High Street', '497', 'Arcade', 12 ,'IN', '55I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'High Street', '491', 'Shipley Travel', 14 ,'IN', '55I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'High Street', '485', 'High St PO', 16 ,'IN', '55I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'Clarendon Rd  N', '425', 'Dene View Rd', 18 ,'IN', '55I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'Clarendon Rd  N', '431', 'Angel St', 20 ,'IN', '55I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'John St', '515', 'John St', 22 ,'IN', '55I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'Arcadia Gdns', '371', 'Aquarium', 24 ,'IN', '55I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'Arcadia Gdns', '377', 'Arcadia Gdns', 26 ,'IN', '55I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'Sea View Rd', '599', 'Botanical Gdns', 28 ,'IN', '55I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('55', 'Oasis', '539', 'Oasis North', 30 ,'IN', '55I');

--65
--OUT

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '614', 'Town Hall', 0 ,'OUT', '65O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '440', 'Odeon Cinema', 2 ,'OUT', '65O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '515', 'John St', 4 ,'OUT', '65O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '584', 'John St', 6 ,'OUT', '65O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '575', 'North Beach', 8 ,'OUT', '65O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '380', 'Barclay St', 10 ,'OUT', '65O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '452', 'Dene View Rd', 12 ,'OUT', '65O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '455', 'Fishermans Inn',14 ,'OUT', '65O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '545', 'Railway Station', 17 ,'OUT', '65O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '554', 'Sanctuary', 20 ,'OUT', '65O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '536', 'Chocolate Factory', 24 ,'OUT', '65O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '533', 'Greyhound Stadium', 26 ,'OUT', '65O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '527', 'Museum Ave E', 28 ,'OUT', '65O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '530', 'Museum Ave W', 30 ,'OUT', '65O');

--chucks duplicate error, ask john 
INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '614', 'Town Hall', 32 ,'OUT', '65O');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '644', 'Town Hall', 0 ,'IN', '65I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '662', 'Museum', 2 ,'IN', '65I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '518', 'Museum Ave E', 4 ,'IN', '65I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '524', 'Greyhound Stadium', 6 ,'IN', '65I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '521', 'Chocolate Factory', 8 ,'IN', '65I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '551', 'Sanctuary', 12 ,'IN', '65I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '548', 'Railway Station', 15 ,'IN', '65I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '482', 'High St Pearl', 18 ,'IN', '65I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '428', 'Barclay St', 20 ,'IN', '65I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '578', 'Bay Hotel', 22 ,'IN', '65I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '581', 'Casino', 24 ,'IN', '65I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '512', 'John St', 26 ,'IN', '65I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '437', 'Grand Hotel', 28 ,'IN', '65I');

INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '443', 'Dyle Lane', 30 ,'IN', '65I');

--chucks error ask john 
INSERT INTO BBT_SERVICE_STOPS (ROUTENO, ROUTINGNAME, STOPREFERENCE, STOPNAME, JOURNEYTIME, DIRECTION, STOPSEQNO)
VALUES('65', ' ', '644', 'Town Hall', 32 ,'IN', '65I');