SELECT STOPREFERENCE, ROUTINGNAME,LOCATION_DESCRIPTION, DESTID, BBT_SERVICE_STOPS.DIRECTION
FROM  BBT_SERVICE_STOPS
INNER JOIN BBT_DESTINATION
ON BBT_SERVICE_STOPS.ROUTENO = BBT_DESTINATION.ROUTENO;
--WHERE ROUTENO ='X91';

SELECT SCHEDULENO, TYPE1, XCOORDINATE, YCOORDINATE
FROM BBT_SCHEDULE
INNER JOIN BBT_DESTINATION
ON BBT_DESTINATION.DESTID = BBT_SCHEDULE.DESTID;